package gcg

var functionsTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: {{.BuildVersion }}
// DO NOT EDIT

{{- range .Functions}}

// {{.Comment}}
type {{.Name}} struct {
	// input	
	{{- range .Fields}}
	{{- if gt (len .Comment) 0}}
	// {{.Comment}}{{- end}}
	{{.Name}} {{if .Optional}} *{{else}} {{end}}{{if .IsArray}}[]{{end}}{{.Type}} {{.Tag}}
	{{- end}}
	// output
	{{.ReturnType}} 
}
{{- end}}
`
