package gcg

var inputTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: {{.BuildVersion }}
// DO NOT EDIT

import (
	"time"
	"encoding/json"
)
var (
	_ = time.Now
	_ = json.Marshal
)

{{- range .Inputs}}

// {{.Name}} is an INPUT_OBJECT. {{.Comment}}
type {{.Name}} struct {
	values map[string]interface{}
}

// New{{.Name}} must be used to create a {{.Name}}.
func New{{.Name}}() {{.Name}} {
	return {{.Name}}{values: map[string]interface{}{}}	
}

{{- range .Fields}}
{{- if gt (len .Comment) 0}}
// {{.Comment}}{{- end}}
func (i {{.StructName}}) {{.Name}}(v {{if .Optional}} *{{else}} {{end}}{{if .IsArray}}[]{{end}}{{.Type}}) {
	i.values["{{.JSONName}}"] = v
}
{{- end}}

func (i {{.Name}}) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.values)
}

{{- end}}
`
