package gcg

var inputTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: {{.BuildVersion }}
// DO NOT EDIT

import (
	"time"
	"encoding/json"
)
var (
	_ = time.Now
	_ = json.Marshal
)

{{- range .Inputs}}

// {{.Name}} is an INPUT_OBJECT. {{.Comment}}
{{- range .Fields}}
// {{.JSONName}}:{{.GraphType}} {{if .Deprecated}}@deprecated{{end}}
{{- end}}
type {{.Name}} map[string]interface{}

{{- range .Fields}}
{{- if gt (len .Comment) 0}}
// {{.Comment}}{{- end}}
// {{.JSONName}}:{{.GraphType}} {{if .Deprecated}}@deprecated{{end}}
func (i {{.StructName}}) {{.Name}}(v {{if .Optional}} *{{else}} {{end}}{{if .IsArray}}[]{{end}}{{.Type}}) {{.StructName}} {
	i["{{.JSONName}}"] = v
	return i
}
{{- end}}

func (i {{.Name}}) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]interface{}(i))
}

{{- end}}
`
