package gcg

var operationsTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/gcg on {{.Created.Format "Mon, 02 Jan 2006 15:04:05 MST" }} 
// DO NOT EDIT

import (
	"time"
	"context"
	"github.com/shurcooL/graphql"
)
var _ = time.Now

type Client struct {
	graphqlClient *graphql.Client
}

{{- range .Operations}}

func (c *Client) {{.FunctionName}}(
	ctx context.Context,
	{{- range .Arguments}}
	{{.Name}} {{if .IsArray}}[]{{end}}{{.Type}},{{- end}})({{if .IsArray}}[]{{end}}{{.ReturnType}},error) {
	var m struct {
		{{.FunctionName}} struct {
			{{.ReturnType}}
		} {{.Tag}}
	}
	vars := map[string]interface{}{
		{{- range .Arguments}}
		"{{.Name}}": {{.Name}},
		{{- end}}
	}
	err := c.graphqlClient.Mutate(ctx, &m, vars)
	return m.{{.FunctionName}}.{{.ReturnType}}, err
}
{{- end }}
`
