package gcg

var operationsTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on {{.Created.Format "Mon, 02 Jan 2006 15:04:05 MST" }} 
// DO NOT EDIT

import (
	"time"
)

var (
	_ = time.Now
)

{{- range .Operations}}

// {{.FunctionName}}Mutation is used for both specifying the query and capturing the response. {{.Comment}}
type {{.FunctionName}}Mutation struct {
	Data struct {
		{{.ReturnType}} {{.ReturnFieldTag}}
	} {{.DataTag}}
}

// Build returns all the parts to send the HTTP requests
func (_m {{.FunctionName}}Mutation) Build(
		{{- range .Arguments}}
		{{.Name}} {{.Type}}, 
		{{- end }}
	) GraphQLRequest { 
	return GraphQLRequest{
		Query: BuildQuery(_m),
		OperationName: "{{.Name}}",
		Variables: map[string]interface{}{
			{{- range .Arguments}}
			"{{.Name}}": {{.Name}},
			{{- end }}
		},
	}
}

{{- end }}
`
