package gcg

var operationsTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/gcg on {{.Created.Format "Mon, 02 Jan 2006 15:04:05 MST" }} 
// DO NOT EDIT

import (
	"time"
)
var _ = time.Now

{{- range .Operations}}

func {{.FunctionName}}(
	{{- range .Arguments}}
	{{.Name}} {{if .IsArray}}[]{{end}}{{.Type}},{{- end}})(result {{if .IsArray}}[]{{end}}{{.ReturnType}}, err error) {
	return
}
{{- end }}
`
