package gcg

var typeTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/gcg on {{.Created.Format "Mon, 02 Jan 2006 15:04:05 MST" }} 
// DO NOT EDIT

import (
	"time"
	"github.com/shurcooL/graphql"
)
var (
	_ = time.Now
	_ = graphql.NewClient
)

{{- range .Types}}

// {{.Name}} is a {{.Kind}}. {{.Comment}}
type {{.Name}} struct {
	{{- range .Fields}}
	{{.Name}} {{if .Optional}} *{{else}} {{end}}{{if .IsArray}}[]{{end}}{{.Type}} {{.Tag}}
	{{- end}}
}
{{- end}}
`
