package gcg

var typeTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: {{.BuildVersion }}
// DO NOT EDIT

import (
	"time"
)
var (
	_ = time.Now
)

{{- range .Types}}

// {{.Name}} is a {{.Kind}}. {{.Comment}}
type {{.Name}} struct {
	{{- range .Fields}}
	{{- if gt (len .Comment) 0}}
	// {{.Comment}}{{- end}}
	{{.Name}} {{if .Optional}} *{{else}} {{end}}{{if .IsArray}}[]{{end}}{{.Type}} {{.Tag}}
	{{- end}}
}
{{- end}}
`
