package gcg

var typeTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/gcg on {{.Created.Format "Mon, 02 Jan 2006 15:04:05 MST" }} 
// DO NOT EDIT

import (
	"time"
)
var _ = time.Now

{{- range .Operations}}

func {{.FunctionName}}()({{if .IsArray}}[]{{end}}{{.ReturnType}},error) {

}

{{- end}}

{{- range .Types}}

// {{.Name}} is a {{.Kind}}
type {{.Name}} struct {
	{{- range .EmbeddedTypes}}
	{{.}}
	{{- end}}
	{{- range .Fields}}
	{{.Name}} {{if .Optional}} *{{else}} {{end}}{{if .IsArray}}[]{{end}}{{.Type}} {{.Tag}}
	{{- end}}
}
{{- end}}

{{- range .Enums}}

// {{.Name}} is an Enum
type {{.Name}} string {{$enumName := .Name}}
const (
{{- range .Values}}
{{$enumName}}_{{.}} = {{$enumName}}("{{.}}")
{{- end}}
)
{{- end}}

type Boolean bool
type String string
type Int int
type JSON interface{}
type ID string
type Duration string
type IString string
type FilterArgument string
type Timestamp time.Time
type FileContent []byte
type Date time.Time
type DateRange struct{}
type OpaqueQuery string
type FileID string
type PartialQuantity string
`
