package gcg

var unionTemplateSrc = `package {{.Package}}
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: {{.BuildVersion }}
// DO NOT EDIT

import (
	"time"
)
var (
	_ = time.Now
)

{{- range .Unions}}

// {{.Name}} is a UNION. {{.Comment}}
type {{.Name}} struct {
	{{- range .Types}}
	{{.}}
	{{- end}}
}
{{- end}}
`
