package tests

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: (devel)
// DO NOT EDIT

import (
	"encoding/json"
	"time"
)

var (
	_ = time.Now
	_ = json.Unmarshal
)

//
// explanation(language:String!,long:Boolean):String!
type ResultExplanationFunction struct {
	Language string `graphql-function-arg:"language" graphql-function-type:"String!"`
	Long     *bool  `graphql-function-arg:"long" graphql-function-type:"Boolean"`
	// Result captures the query response part of this function.
	Result string `graphql:"inline"`
}

func (f *ResultExplanationFunction) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &f.Result)
}
