package tests

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: (devel)
// DO NOT EDIT

import (
	"encoding/json"
	"time"
)

var (
	_ = time.Now
	_ = json.Marshal
)

// ResultInput is an INPUT_OBJECT. comment for ResultInput
type ResultInput struct {
	values map[string]interface{}
}

// NewResultInput must be used to create a ResultInput.
func NewResultInput() ResultInput {
	return ResultInput{values: map[string]interface{}{}}
}

// comment for when
func (i ResultInput) When(v CustomDate) {
	i.values["when"] = v
}

// comment for unused
func (i ResultInput) Unused(v *string) {
	i.values["unused"] = v
}

func (i ResultInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.values)
}
