package tests

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: (devel)
// DO NOT EDIT

import (
	"encoding/json"
	"time"
)

var (
	_ = time.Now
	_ = json.Marshal
)

// ResultInput is an INPUT_OBJECT. comment for ResultInput
type ResultInput map[string]interface{}

// comment for when
func (i ResultInput) When(v CustomDate) ResultInput {
	i["when"] = v
	return i
}

// comment for unused
func (i ResultInput) Unused(v *string) ResultInput {
	i["unused"] = v
	return i
}

func (i ResultInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]interface{}(i))
}
