package tests

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: v1.0.1+dirty
// DO NOT EDIT

import (
	"encoding/json"
	"time"
)

var (
	_ = time.Now
	_ = json.Marshal
)

// ResultInput is an INPUT_OBJECT. comment for ResultInput
// when:Date!
// unused:String @deprecated
type ResultInput map[string]any

// comment for when
// when:Date!
func (i ResultInput) When(v CustomDate) ResultInput {
	i["when"] = v
	return i
}

// comment for unused
// unused:String @deprecated
func (i ResultInput) Unused(v *string) ResultInput {
	i["unused"] = v
	return i
}

func (i ResultInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]any(i))
}
