package tests

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: (devel)
// DO NOT EDIT

import (
	"time"
)

var (
	_ = time.Now
)

// Identified is a INTERFACE.
type Identified struct {
	ID interface{} `graphql:"id" json:"id,omitempty"`
}

// Result is a OBJECT.
type Result struct {
	// will map to CustomDate
	When        *CustomDate             `graphql:"when" json:"when,omitempty"`
	Explanation *ResultExplanationField `graphql:"explanation" json:"explanation,omitempty"`
	ID          interface{}             `graphql:"id" json:"id,omitempty"`
	// GraphQLTypename is a metadata field
	GraphQLTypename string `graphql:"__typename" json:"__typename,omitempty"`
}
