package tweet
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on Tue, 25 Jan 2022 21:46:00 CET 
// DO NOT EDIT

// 
type TweetRespondersFunction struct {
	// input
	Limit  int32 `graphql-function-arg:"limit"`
	// output
	User 
}
