package tweet
<<<<<<< HEAD
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on Thu, 27 Jan 2022 10:29:29 CET 
=======
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on Thu, 27 Jan 2022 09:56:20 CET 
>>>>>>> main
// DO NOT EDIT

// 
type TweetRespondersFunction struct {
	// input
	Limit  int32 `graphql-function-arg:"limit"`
	// output
	User 
}
