package tweet
// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on Thu, 27 Jan 2022 09:43:05 CET 
// DO NOT EDIT

// 
type TweetRespondersFunction struct {
	// input
	Limit  int32 `graphql-function-arg:"limit"`
	// output
	User 
}
