package tweet

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on Tue, 25 Jan 2022 13:29:11 CET
// DO NOT EDIT

import (
	"time"
)

var (
	_ = time.Now
)

var Query = query{}

type query struct{}
