package tweet

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on Mon, 24 Jan 2022 17:18:52 CET
// DO NOT EDIT

// Url is a Scalar.
type Url string

// Date is a Scalar.
type Date string
