package tweet

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on Tue, 25 Jan 2022 13:29:11 CET
// DO NOT EDIT

// Url is a Scalar.
type Url string

// NewUrl returns a pointer to a Url value.
// Use type conversion instead e.g. v := Url(s) if you need the non-pointer value.
func NewUrl(s string) *Url { v := Url(s); return &v }

// Date is a Scalar.
type Date string

// NewDate returns a pointer to a Date value.
// Use type conversion instead e.g. v := Date(s) if you need the non-pointer value.
func NewDate(s string) *Date { v := Date(s); return &v }
