package tweet

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on Sun, 23 Jan 2022 22:35:39 CET
// DO NOT EDIT

// Url is a Scalar.
type Url string

// Date is a Scalar.
type Date string
