package tweet

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg on Thu, 27 Jan 2022 15:44:34 CET
// DO NOT EDIT

import (
	"time"
)

var (
	_ = time.Now
)

// ValueFilterValuesFilterRangeFilterUnion is a UNION.
type ValueFilterValuesFilterRangeFilterUnion struct {
	Value  string   `graphql:"value" json:"value,omitempty"`
	Values []string `graphql:"values" json:"values,omitempty"`
	//
	// Filter the values from and including this value.
	// If this field is not set then the filter is applied without a minimum value.
	From *float64 `graphql:"from" json:"from,omitempty"`
	//
	// Filter the values up to and including this value.
	// If this field is not set then the filter is applied without a maximum value.
	To *float64 `graphql:"to" json:"to,omitempty"`
}
