package tweet

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: (dev)
// DO NOT EDIT

import (
	"time"
)

var (
	_ = time.Now
)

// FilterValue is a UNION.
type FilterValue struct {
	ValueFilter
	ValuesFilter
	RangeFilter
}
