package tests

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: (dev)
// DO NOT EDIT

import (
	"time"
)

var (
	_ = time.Now
)

// CreateResultMutation is used for both specifying the query and capturing the response. createResult(): Result
type CreateResultMutation struct {
	Errors Errors `json:"errors"`
	Data   struct {
		ID `graphql:"createResult(input: $input)" json:"createResult"`
	} `graphql:"mutation"`
}

// Build returns a GraphQLRequest with all the parts to send the HTTP request.
func (_m CreateResultMutation) Build(
	_input ResultInput,
) GraphQLRequest {
	_typedVars := map[string]valueAndType{
		"input": {value: _input, graphType: "ResultInput!"},
	}
	return buildRequest("mutation", "createResult", _m.Data, _typedVars)
}
