package tests

// generated by github.com/emicklei/graphql-client-gen/cmd/gcg version: (dev)
// DO NOT EDIT
// ID can by any type, typically a string or int64
type ID interface{}

// URL is a Scalar.
type URL string

// NewURL returns a pointer to a URL value.
// Use type conversion instead e.g. v := URL(s) if you need the non-pointer value.
func NewURL(s string) *URL { v := URL(s); return &v }
